export const MODULE_NAME = 'POSTS';

export const GET_USERS_POSTS = `[${MODULE_NAME}] GET_USERS_POSTS`;
export const GET_POSTS = `[${MODULE_NAME}] GET_POSTS`;
export const SET_POSTS = `[${MODULE_NAME}] SET_POSTS`;
export const SET_USERS_POSTS = `[${MODULE_NAME}] SET_USERS_POSTS`;
export const SEARCH_POSTS = `[${MODULE_NAME}] SEARCH_POSTS`;
export const UPDATE_POST = `[${MODULE_NAME}] UPDATE_POST`;
export const CREATE_POST = `[${MODULE_NAME}] CREATE_POST`;
export const DELETE_POST = `[${MODULE_NAME}] DELETE_POST`;
export const ADD_NEW_POST = `[${MODULE_NAME}] ADD_NEW_POST`;
export const SELECTED_POST = `[${MODULE_NAME}] SELECTED_POST`;
export const CLEAR_SELECTED_POST = `[${MODULE_NAME}] CLEAR_SELECTED_POST`;
export const UPDATE_SELECTED_POST = `[${MODULE_NAME}] UPDATE_SELECTED_POST`;  